### ISSUE TITLE
Search functionality addition

### ISSUE THREAD

**Issue by anantkataria** [Janvipatel1102/25-Online-Grocery-App#1]
this issue is about working to add search functionality to the main app of Tiwarimart.

**Comment by Janvipatel1102** [comment]
@savage-9  Search Functionality Done.

**Comment by anantkataria** [comment]
checked it, nicely done

**Comment by anantkataria** [comment]
@Janvipatel1102,could you make your separate branch and upload your work on that. Than we will merge it to the main branch. Thank you

**Comment by Janvipatel1102** [comment]
@savage-9  I have created my branch and now on words, I will upload my work on that. Currently, it is even with the Main branch.
Should I delete my work from the Main branch and then create a merge request? or is it fine for now?

**Comment by anantkataria** [comment]
It will be better if you delete from main branch for now and upload it into your branch @Janvipatel1102

**Comment by anantkataria** [comment]
@Janvipatel1102 i saw the app you sent me. It is almost exactly how it should be. Now you could clone the Tiwarimart app and try to add this functionality into that app

**Comment by Janvipatel1102** [comment]
@savage-9 can you please add some products so I can check that sort working properly or not.

**Comment by anantkataria** [comment]
Yes, i have added 3 new demo products

**Comment by Janvipatel1102** [comment]
@savage-9  search functionality added with sort and filters. Please Check it out once.

**Comment by anantkataria** [comment]
will do

**Comment by anantkataria** [comment]
@Janvipatel1102 , we should do a meeting, so that we can integrate it into the app

**Comment by Janvipatel1102** [comment]
yes ,when ?

**Comment by anantkataria** [comment]
Search functionality is added into the app successfully
