### ISSUE TITLE
lab 8 q1 diagram 3

### ISSUE THREAD

**Issue by anantkataria** [Janvipatel1102/25-Online-Grocery-App#13]

**Comment by VrajSoni** [comment]
[Lab8_Q1_3.pdf](https://github.com/Janvipatel1102/25-Online-Grocery-App/files/6273307/Lab8_Q1_3.pdf)

**Comment by anantkataria** [comment]
could you add this in the lab 8 folder in assignments folder of the repository

**Comment by VrajSoni** [comment]
done

**Comment by anantkataria** [comment]
okay
