### ISSUE TITLE
Game functionality addition

### ISSUE THREAD

**Issue by anantkataria** [Janvipatel1102/25-Online-Grocery-App#2]
This issue is about working to add functionality of playing games and earning points.

**Comment by VrajSoni** [comment]
Embedding of an unity game into android studio successful.

**Comment by anantkataria** [comment]
dear @VrajSoni, the games you have added are pretty big by the size margin. It is around 45 MB. Could you reduce the size?

**Comment by anantkataria** [comment]
And one more thing, we should add some quiz type of games too!! That would be exciting

**Comment by VrajSoni** [comment]
Will try to reduce the app size as much as possible

**Comment by VrajSoni** [comment]
> And one more thing, we should add some quiz type of games too!! That would be exciting

Ya, that's a good idea.
Those games will have lesser size by default as well.

**Comment by VrajSoni** [comment]
Maybe we can add a roulette game, where the customer spins a roulette to get some points or some freebie groceries if they are lucky

**Comment by anantkataria** [comment]
Yea, that sounds awesome!

**Comment by VrajSoni** [comment]
I will look forward to make some other luck based games as well to provide some more options to the customer.

**Comment by anantkataria** [comment]
Yeah
Great

**Comment by VrajSoni** [comment]
The games made in unity when embedded into android studio are having a very large file size. So, we should make the games in android studio itself.

**Comment by anantkataria** [comment]
okay, that would work too

**Comment by VrajSoni** [comment]
Roulette Game made in android studio.

**Comment by VrajSoni** [comment]
Currently working on Slot Machine Game.
