### ISSUE TITLE
Add customer support 

### ISSUE THREAD

**Issue by anantkataria** [Janvipatel1102/25-Online-Grocery-App#3]
This issue works on adding customer support (customer care, helpline) to the main app TiwariMart

**Comment by anantkataria** [comment]
what is the status @Roh15 bro?

**Comment by Roh15** [comment]
@savage-9 I have created the dummy app in python. Will work on the integration into our app very soon.

**Comment by anantkataria** [comment]
okay! great

**Comment by anantkataria** [comment]
Dear @Roh15 bro, i think we should add one to one customer chat functionality with the admin (or merchant), so that customer can directly ping the admin and solve the problem in one to one chat!!

**Comment by anantkataria** [comment]
@Roh15

**Comment by anantkataria** [comment]
> 
> 
> Dear @Roh15 bro, i think we should add one to one customer chat functionality with the admin (or merchant), so that customer can directly ping the admin and solve the problem in one to one chat!!

What's the progress man?

**Comment by Roh15** [comment]
Sounds like a good idea @savage-9

**Comment by Roh15** [comment]
Finished making a chat application (single activity). Finished the firebase course. Hopefully will be straightforward now.

**Comment by anantkataria** [comment]
Yess

**Comment by anantkataria** [comment]
GG
