### ISSUE TITLE
Create design and XML 

### ISSUE THREAD

**Issue by anantkataria** [Janvipatel1102/25-Online-Grocery-App#5]
This issue works on creating design and XML layouts for the main app TiwariMart and TiwariMartAdmin

**Comment by anantkataria** [comment]
What is status on making XMLs @Parita16 , @ParthKatrodiya

**Comment by ParthKatrodiya** [comment]
@Janvipatel1102 @Roh15 @Tanishq33 @venu132k @VrajSoni Upload all the XMLs here

**Comment by Parita16** [comment]
Designs are done for the onboarding, sign-up, login, authentication, orders, cart, checkout, and product pages. Go through them and let us know if something needs to change

**Comment by Janvipatel1102** [comment]
@Roh15  Design  My Order and Select Location Screens Layout.
@Tanishq33  Design Order Summary and Sign-Up Screens Layout.
@venu132k  Design Product Page, Splash Screens Layout.
@smit-kumbhani  Design Categories and Onboarding Screens Layout.
@YTX-22 Design Verification and Number Screens Layout.
@Janvipatel1102  Design Cart and Log in Screens Layout.

**Comment by ParthKatrodiya** [comment]
'Search Results' screen is ready now. Filter and sort overlays yet to be done

**Comment by anantkataria** [comment]
Hello all, how is the work on XML?

**Comment by Janvipatel1102** [comment]
Mine is done, how to upload it?

**Comment by anantkataria** [comment]
upload it on your branch, in xml file format

**Comment by Janvipatel1102** [comment]
cart and login screens added.

**Comment by YTX-22** [comment]
Verification screen done.
