### ISSUE TITLE
Payment Gateway integration

### ISSUE THREAD

**Issue by anantkataria** [Janvipatel1102/25-Online-Grocery-App#6]
make a toy app which has all payment methods (cards, upis, pay later, etc...) integrated in it

**Comment by anantkataria** [comment]
Anybody has any idea on this, adding payment gateway ?

**Comment by Janvipatel1102** [comment]
no idea.

**Comment by YTX-22** [comment]
Reference to add payment gateway to our app:
https://razorpay.com/docs/payment-gateway/android-integration/standard/
